#!/bin/sh

# /usr/bin/autorandr -c
# env for HiDPI
export WINIT_X11_SCALE_FACTOR=1.5
export GDK_SCALE=2
export GDK_DPI_SCALE=0.75
export QT_SCREEN_SCALE_FACTORS="1.5"
export QT_FONT_DPI=140
export QT_SCALE_FACTOR=1.5
export QT_AUTO_SCREEN_SCALE_FACTOR=1

export GTK_THEME=Arc:dark
export GDK_BACKEND=x11


exec i3 -c "$SESSION_CONF/i3config"
