hl.on("hyprland.start", function()
	hl.exec_cmd("wbg --stretch ~/Pictures/wallpapers/karsten-wurth-7BjhtdogU3A-unsplash.jpg")
	hl.exec_cmd("RUST_LOG='debug' /usr/bin/hyprland-per-window-layout > /tmp/hyprland-per-window-layout.log 2>&1")
	hl.exec_cmd("/bin/sh -c \"secret-tool lookup 'keepass' 'default' | keepassxc --pw-stdin ~/KeePass/database.kdbx\"")
	hl.exec_cmd("/bin/bash ~/Downloads/Telegram\\ Desktop/unzip_here.sh")
	hl.exec_cmd("/usr/lib/thunderbird/thunderbird")
end)
