#!/bin/sh

/usr/bin/autorandr -c

if xrandr --listmonitors | grep ' 2560' ; then
	# env for regular displays
	export GDK_SCALE=""
	export QT_AUTO_SCREEN_SCALE_FACTOR=""
	export QT_SCREEN_SCALE_FACTORS=""
	export QT_FONT_DPI=100
else
	# env for HiDPI
	export GDK_SCALE=2
	export QT_AUTO_SCREEN_SCALE_FACTOR=1
	export QT_SCREEN_SCALE_FACTORS="2"
	export QT_FONT_DPI=200
fi

exec i3 -c $HOME/.config/potato/i3config
