general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
}

# ---------- Background ----------
background {
    monitor =
    path = ~/.config/hypr/patrick-fore-iOiaqY7eZsY-unsplash.jpg
    blur_passes = 2
    blur_size = 2
    # noise = 0.015
    contrast = 1.05
    # vibrancy = 0.25
    # vibrancy_darkness = 1.3
}

# ---------- Clock ----------
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = Adwaita Sans Black
    color = rgba(255, 255, 255, 0.2)
    position = 0, -160
    halign = center
    valign = center
}

image {
    monitor = 
    path = ~/.config/hypr/terminal.png
    border_size = 0
    position = 0, 0
    size = 500
    rounding = 0
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:10000] echo "$(neofetch --stdout --cpu_speed off --cpu_temp C --memory_percent on --package_managers off --disable gpu song title packages kernel term --underline off)"
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    color = rgba(198, 120, 221, 0.8)
    position = 18, -42
    halign = left
    valign = top
}

# ---------- Date ----------
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    font_size = 34
    font_family = Adwaita Sans Bold
    color = rgba(255, 255, 255, 0.2)
    position = 0, -260
    halign = center
    valign = center
}

# ---------- Keyboard Layout ----------
label {
    monitor = eDP-1
    text = $LAYOUT [$ATTEMPTS] $FAIL
    font_size = 18
    font_family = Adwaita Sans Medium
    color = rgba(250, 250, 250, 0.4)

    position = 0, 20
    halign = left
    valign = bottom
}

# ---------- Sleep Button ----------
label {
    monitor =
    text = 󰒲
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    color = rgba(250, 250, 250, 0.4)

    position = -20, 20
    halign = right
    valign = bottom

    onclick = systemctl suspend
}

# ---------- Slack Unread ----------
label {
    monitor =
    text = cmd[update:30] ~/.config/hypr/slack.sh
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    color = rgba(10, 135, 30, 0.8)

    position = 0, -40
    halign = center
    valign = top
}
