general {
    lock_cmd = ~/.local/bin/lock
    before_sleep_cmd = ~/.local/bin/lock
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 600
    on-timeout = ~/.local/bin/lock
}
