splash = false
ipc = false

wallpaper {
    monitor = 
    path = /usr/share/backgrounds/Fuji_san_by_amaral.png
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/karsten-wurth-7BjhtdogU3A-unsplash.jpg
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/karsten-wurth-7BjhtdogU3A-unsplash.jpg
}
