#!/bin/sh
# hook after pull-merge

alias dotf="git --git-dir=$HOME/dotfiles --work-tree=$HOME"

# get list of changed files
PREV_MEGRE_ID=$(dotf reflog -n 2 | tail -1 | rg -oP "^\w+")
CHANGED_FILES=$(dotf diff --name-only $PREV_MEGRE_ID HEAD)

# install-update hooks
echo $CHANGED_FILES | rg "^hooks/" && \
	cp -f ~/hooks/* ~/dotfiles/hooks/

# update installed nvim plugins
echo $CHANGED_FILES | rg "^.config/nvim/plugin/packer.lua" && \
	nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
