hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dunst")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/.config/hypr/xdg.sh >> /tmp/xdg.sh.log 2>&1")
	hl.exec_cmd("wl-paste -t text --watch clipman store --no-persist")
	hl.exec_cmd("Thunar --daemon")
	hl.exec_cmd("~/.config/hypr/start-in-tray.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd('foot --title workspace10 -e zsh -c "pull-dotfiles"')
end)
