hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@60", position = "0x0", scale = "1" })
hl.monitor({ output = "desc:BNQ BenQ PD2705U 89P03368019", mode = "3840x2160@60", position = "0x0", scale = "1.5" })
hl.monitor({ output = "desc:WSX SGD SX8 0x00000321", mode = "preferred", position = "auto", scale = "1", mirror = "eDP-1" })
hl.monitor({ output = "DP-2", disabled = true })
hl.monitor({ output = "desc:BOE 0x094C", mode = "1920x1200@60", position = "0x1440", scale = "1" })

hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "2", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "4", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-1" })
