#!/bin/sh

/usr/bin/autorandr -c

export TERMINAL=alacritty
export EDITOR=nvim
export WINIT_X11_SCALE_FACTOR=1.3

# if xrandr --listmonitors | grep ' 2560' ; then
# 	# env for regular displays
# 	export GDK_SCALE=""
# 	export QT_AUTO_SCREEN_SCALE_FACTOR=""
# 	export QT_SCREEN_SCALE_FACTORS=""
# 	export QT_FONT_DPI=100
# else
# 	# env for HiDPI
# 	export GDK_SCALE=2
# 	export QT_AUTO_SCREEN_SCALE_FACTOR=1
# 	export QT_SCREEN_SCALE_FACTORS="2"
# 	export QT_FONT_DPI=200
# fi

if [ -f $HOME/.config/crab/.profile ]; then
	# env variables ($PATH)
  source $HOME/.config/crab/.profile
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export XDG_CURRENT_DESKTOP=i3
exec i3 -c $HOME/.config/crab/i3config




# How to setup autologin in tty
# https://wiki.archlinux.org/title/getty
